initial commit
logzio/logzio-google-metrics pull request #1
Opened 2022-12-13 16:49 UTC by resdenia

Metrics from google services to logz.io
Using APIs:
- Cloud Function
- Monitoring API
- Job Scheduler

2022-12-19 12:34 UTC, Doron-Bargo requested changes
Great, Please see my comments

2022-12-19 12:34 UTC, Doron-Bargo commented on README.md
> +Give your metrics a few minutes to get from your system to ours, and then open [Kibana](https://app.logz.io/#/dashboard/metrics).
Why open kibana?

2022-12-19 12:34 UTC, Doron-Bargo commented on run.sh
> +        echo -e "\033[0;31mrun.sh (1): Region for Google Cloud Platform is missing please rerun the script with the relevant parameters\033[0;37m"
Not sure this error is correct

2022-12-19 12:34 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Failed to download telegraf  ..."
What is the connection to telegraf?

2022-12-19 12:34 UTC, Doron-Bargo commented on run.sh
> +    echo -e " --region=<region>                   Region where you want to upload Cloud Funtion."
Not clear which region is this one please change to gcp_region

2022-12-19 12:34 UTC, Doron-Bargo commented on README.md
> +| region       | Region where you want to upload Cloud Function. \*`Requires for Deploy to Cloud option for platform`.                                                         |
Its need to be more clear its gcp regions and not logzio
Also is it the name of the region or the id?

2022-12-19 12:34 UTC, Doron-Bargo commented on run.sh
> +#   metric_type - Region where user want to upload Cloud Funtion.
This comment is not correct

2022-12-19 12:34 UTC, Doron-Bargo commented on run.sh
> +#   type -  Log type. Help classify logs into different classifications
log type?

2023-01-03 11:03 UTC, Doron-Bargo requested changes
Please check my comments

2023-01-03 11:03 UTC, Doron-Bargo commented on README.md
> +3. Set the `project id` for the project that you want to send logs from:
collect metrics from

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Failed to get gcloud CLI. Please install Gcloud and login to proper account from where you want to send metrics..."
Failed to use

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +    echo -e "[INFO] [$(date +"%Y-%m-%d %H:%M:%S")] Validation of arguments passed."
passed successfully

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +function download_telegraf(){
Please replace telegraf to Telegraf

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Failed to move telegraf to function folder..."
to the function's folder

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Failed to remove telegraf folder  ..."
remove the Telegraf folder

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Error to remove..."
Its not clear

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[INFO] [$(date +"%Y-%m-%d %H:%M:%S")] Project ID=$project_id where will launch integration."
where integration will be launched

2023-01-03 11:03 UTC, Doron-Bargo commented on run.sh
> +        echo -e "[ERROR] [$(date +"%Y-%m-%d %H:%M:%S")] Failed to move telegraf to function folder..."
to the function's folder

2023-01-09 07:54 UTC, Doron-Bargo requested changes
One small comment and we are done

2023-01-09 07:54 UTC, Doron-Bargo commented on run.sh
> +    rm -rf ./function_cloud/telegraf.conf
why you need to remove the Telegraf file and not just overwrite it?

2023-01-09 08:31 UTC, resdenia commented on run.sh
> +    rm -rf ./function_cloud/telegraf.conf
Yes, it's a good improvement.

2023-01-09 09:32 UTC, Doron-Bargo approved these changes
lgtm

2023-01-09 09:53 UTC, merged